# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\x0ereconstruction\"\'\n\x12HealthCheckRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"Q\n\x13HealthCheckResponse\x12\x10\n\x08is_ready\x18\x01 \x01(\x08\x12\x16\n\x0e\x63uda_available\x18\x02 \x01(\x08\x12\x10\n\x08gpu_name\x18\x03 \x01(\t\"A\n\x0c\x46rameRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\"@\n\rFrameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1e\n\x16\x64\x65tected_objects_count\x18\x02 \x01(\x05\x32\xbc\x01\n\x15ReconstructionService\x12V\n\x0bHealthCheck\x12\".reconstruction.HealthCheckRequest\x1a#.reconstruction.HealthCheckResponse\x12K\n\x0cProcessFrame\x12\x1c.reconstruction.FrameRequest\x1a\x1d.reconstruction.FrameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=34
  _globals['_HEALTHCHECKREQUEST']._serialized_end=73
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=75
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=156
  _globals['_FRAMEREQUEST']._serialized_start=158
  _globals['_FRAMEREQUEST']._serialized_end=223
  _globals['_FRAMERESPONSE']._serialized_start=225
  _globals['_FRAMERESPONSE']._serialized_end=289
  _globals['_RECONSTRUCTIONSERVICE']._serialized_start=292
  _globals['_RECONSTRUCTIONSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
