# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\x0bobjectforge\"i\n\x0c\x46rameRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"e\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\r\n\x05label\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\"p\n\rFrameResponse\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12\x32\n\x10\x64\x65tected_objects\x18\x02 \x03(\x0b\x32\x18.objectforge.BoundingBox\x12\x15\n\rtarget_locked\x18\x03 \x01(\x08\"\"\n\rStatusRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\xbd\x01\n\x0cStatusUpdate\x12.\n\x05state\x18\x01 \x01(\x0e\x32\x1f.objectforge.StatusUpdate.State\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x13progress_percentage\x18\x03 \x01(\x02\"O\n\x05State\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\x0c\n\x08SCANNING\x10\x02\x12\x11\n\rPROCESSING_3D\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x32\xaa\x01\n\x13ObjectForgePipeline\x12\x45\n\x0cProcessFrame\x12\x19.objectforge.FrameRequest\x1a\x1a.objectforge.FrameResponse\x12L\n\x11GetPipelineStatus\x12\x1a.objectforge.StatusRequest\x1a\x19.objectforge.StatusUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=31
  _globals['_FRAMEREQUEST']._serialized_end=136
  _globals['_BOUNDINGBOX']._serialized_start=138
  _globals['_BOUNDINGBOX']._serialized_end=239
  _globals['_FRAMERESPONSE']._serialized_start=241
  _globals['_FRAMERESPONSE']._serialized_end=353
  _globals['_STATUSREQUEST']._serialized_start=355
  _globals['_STATUSREQUEST']._serialized_end=389
  _globals['_STATUSUPDATE']._serialized_start=392
  _globals['_STATUSUPDATE']._serialized_end=581
  _globals['_STATUSUPDATE_STATE']._serialized_start=502
  _globals['_STATUSUPDATE_STATE']._serialized_end=581
  _globals['_OBJECTFORGEPIPELINE']._serialized_start=584
  _globals['_OBJECTFORGEPIPELINE']._serialized_end=754
# @@protoc_insertion_point(module_scope)
