# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_pb2 as pipeline__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectForgePipelineStub:
    """Service running on the Python AI Engine
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFrame = channel.unary_unary(
                '/objectforge.ObjectForgePipeline/ProcessFrame',
                request_serializer=pipeline__pb2.FrameRequest.SerializeToString,
                response_deserializer=pipeline__pb2.FrameResponse.FromString,
                _registered_method=True)
        self.GetPipelineStatus = channel.unary_stream(
                '/objectforge.ObjectForgePipeline/GetPipelineStatus',
                request_serializer=pipeline__pb2.StatusRequest.SerializeToString,
                response_deserializer=pipeline__pb2.StatusUpdate.FromString,
                _registered_method=True)


class ObjectForgePipelineServicer:
    """Service running on the Python AI Engine
    """

    def ProcessFrame(self, request, context):
        """Bi-directional or unary stream for camera frame processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipelineStatus(self, request, context):
        """Stream service state / pipeline notifications to the UI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectForgePipelineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFrame,
                    request_deserializer=pipeline__pb2.FrameRequest.FromString,
                    response_serializer=pipeline__pb2.FrameResponse.SerializeToString,
            ),
            'GetPipelineStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPipelineStatus,
                    request_deserializer=pipeline__pb2.StatusRequest.FromString,
                    response_serializer=pipeline__pb2.StatusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'objectforge.ObjectForgePipeline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('objectforge.ObjectForgePipeline', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectForgePipeline:
    """Service running on the Python AI Engine
    """

    @staticmethod
    def ProcessFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectforge.ObjectForgePipeline/ProcessFrame',
            pipeline__pb2.FrameRequest.SerializeToString,
            pipeline__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipelineStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/objectforge.ObjectForgePipeline/GetPipelineStatus',
            pipeline__pb2.StatusRequest.SerializeToString,
            pipeline__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
